Correct urls for links to npm packages
stylelint/awesome-stylelint pull request #63
Opened 2023-12-21 08:47 UTC by firefoxic

> Which issue, if any, is this issue related to?

I hope I've understood the [request](https://github.com/stylelint/awesome-stylelint/pull/62#issuecomment-1865303274) correctly.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2023-12-21 08:54 UTC, ybiquitous reviewed
Thanks for opening the pull request! If no other downsides, can you update other links to refer npmjs.com, too? I think it should be more consistent.

2023-12-21 14:42 UTC, firefoxic commented
I wanted to make it prettier. Didn't happen... 🤭

2023-12-21 14:47 UTC, firefoxic commented
I clicked through all the links, and found some deprecated packages among them. I changed them to new ones.

2023-12-21 17:27 UTC, jeddy3 requested changes
> I clicked through all the links, and found some deprecated packages among them. I changed them to new ones.

Thank you for doing that! It must've taken some time.

I've suggested a few changes to the plugin descriptions to make them consistent. Otherwise, it LGTM.

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [@stylistic/stylelint-plugin](https://www.npmjs.com/package/@stylistic/stylelint-plugin) - A collection of stylistic rules that have been removed from Stylelint@16.
```suggestion
- [@stylistic/stylelint-plugin](https://www.npmjs.com/package/@stylistic/stylelint-plugin) - Enforce stylistic conventions by porting the rules removed in Stylelint 16.0.0 (Pack)
```

Let's continue the conventions of using:

- "(Pack)" for collections
- descriptions that, where possible, align with our conventions for rule descriptions

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [stylelint-color-format](https://www.npmjs.com/package/stylelint-color-format) - Convert HEX colors to either RGB or HSL.
```suggestion
- [stylelint-color-format](https://www.npmjs.com/package/stylelint-color-format) - Enforce HEX, RGB or HSL colors.
```

2023-12-21 17:27 UTC, jeddy3 commented on README.md
>  - [stylelint-high-performance-animation](https://github.com/kristerkari/stylelint-high-performance-animation) - Avoid low-performance animation and transition properties.
```suggestion
- [stylelint-high-performance-animation](https://github.com/kristerkari/stylelint-high-performance-animation) - Disallow low-performance animation and transition properties.
```

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [stylelint-order](https://www.npmjs.com/package/stylelint-order) - Order things like properties.
```suggestion
- [stylelint-order](https://www.npmjs.com/package/stylelint-order) - Enforce a specific order for things like properties (Pack).
```

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [stylelint-plugin-defensive-css](https://www.npmjs.com/package/stylelint-plugin-defensive-css) - A Stylelint plugin for enforcing defensive CSS best practices.
```suggestion
- [stylelint-plugin-defensive-css](https://www.npmjs.com/package/stylelint-plugin-defensive-css) - Enforce defensive CSS best practices (Pack).
```

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [stylelint-plugin-logical-css](https://www.npmjs.com/package/stylelint-plugin-logical-css) - A Stylelint plugin to enforce logical CSS properties, values and units.
```suggestion
- [stylelint-plugin-logical-css](https://www.npmjs.com/package/stylelint-plugin-logical-css) - Enforce logical CSS properties, values and units (Pack).
```

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [stylelint-scss](https://www.npmjs.com/package/stylelint-scss) - SCSS-specific custom rules (Pack).
```suggestion
- [stylelint-scss](https://www.npmjs.com/package/stylelint-scss) - Enforce SCSS-specific conventions (Pack).
```

2023-12-21 17:27 UTC, jeddy3 commented on README.md
> +- [stylelint-stylus](https://www.npmjs.com/package/stylelint-stylus) - Stylelint plugin for Stylus.
```suggestion
- [stylelint-stylus](https://www.npmjs.com/package/stylelint-stylus) - Enforce Stylus-specific conventions.
```

2023-12-21 17:58 UTC, jeddy3 approved these changes
LGTM, thank you!

2023-12-22 00:49 UTC, ybiquitous approved these changes
Great! Thanks a lot! 👏🏼 

---

By the way, this awesome list will be published on our website. Then people will find the list more easily. See https://github.com/stylelint/stylelint.io/issues/370

2023-12-22 00:50 UTC, merged