Add stylistic config
stylelint/awesome-stylelint pull request #64
Opened 2023-12-23 15:37 UTC by firefoxic

> Which issue, if any, is this issue related to?

None, as it's a documentation fix.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

2023-12-23 15:41 UTC, firefoxic commented
Maybe `for Stylelint` is not needed 🤔

2023-12-23 17:25 UTC, jeddy3 requested changes

2023-12-23 17:25 UTC, jeddy3 commented on README.md
> +- [@stylistic/stylelint-config](https://www.npmjs.com/package/@stylistic/stylelint-config) - The stylistic shareable config for Stylelint.
```suggestion
- [@stylistic/stylelint-config](https://www.npmjs.com/package/@stylistic/stylelint-config) - The stylistic shareable config for `@stylistic/stylelint-plugin`.
```

Let's connect it to the plugin.

2023-12-23 17:43 UTC, jeddy3 approved these changes

2023-12-24 04:08 UTC, ybiquitous approved these changes

2023-12-24 04:08 UTC, merged