Categorizing plugins
stylelint/awesome-stylelint pull request #81
Opened 2024-11-11 21:17 UTC by blyedev

> Which issue, if any, is this issue related to?

#80

> Is there anything in the PR that needs further explanation?

I could use input on the categories, this is merely a first draft. Even in this state though I find it substantially better than the status quo

2024-11-12 00:24 UTC, ybiquitous commented
Thanks, I love this categorizing. 👍🏼 

Can you resolve conflicts?

2024-11-12 10:33 UTC, blyedev commented
> Thanks, I love this categorizing. 👍🏼
> 
> Can you resolve conflicts?

Done

2024-11-12 10:33 UTC, blyedev commented
Closes #80

2024-11-12 12:33 UTC, ybiquitous requested changes
Can you sort plugins alphabetically?

2024-11-12 12:45 UTC, blyedev commented
> Can you sort plugins alphabetically?

Done

2024-11-12 13:00 UTC, blyedev commented
Actually wait I just realized I messed up the original rebase that's why I still had conflicts, let me rewrite history so it's cleaner

2024-11-12 13:01 UTC, ybiquitous commented
Ah, keeping the commits as-is is fine. We will squash and merge PRs.

2024-11-12 13:03 UTC, ybiquitous commented on README.md
> +### Nesting, and specificity
[suggestion] How about trimming a comma?

```suggestion
### Nesting and specificity
```

2024-11-12 13:11 UTC, ybiquitous commented
Thank you, overall LGTM 👍🏼 

@jeddy3 If you're interested and have some time, please provide feedback.

2024-11-12 13:20 UTC, blyedev commented
> Ah, keeping the commits as-is is fine. We will squash and merge PRs.

It's a personal preference so that I can review my own commit history properly, so excuse all the force pushes its my first time contributing to two pr's on one fork.

Otherwise all requested changes are fixed, added 2 fixes too

2024-11-12 16:00 UTC, jeddy3 approved these changes
@blyedev Thanks for the pull request and for doing the bulk of the work.

Categorisation is hard, and some plugin packs don't fit neatly into one category, so we've avoided doing it so far. However, it is an improvement for the user. And, going forward, plugin authors can place their plugins into the most appropriate category.

I've pushed a commit to move a few things around based on what I know about the plugins. It looks good enough to me.

2024-11-12 16:07 UTC, blyedev commented
> @blyedev Thanks for the pull request and for doing the bulk of the work.
> 
> Categorisation is hard, and some plugin packs don't fit neatly into one category, so we've avoided doing it so far. However, it is an improvement for the user. And, going forward, plugin authors can place their plugins into the most appropriate category.
> 
> I've pushed a commit to move a few things around based on what I know about the plugins. It looks good enough to me.

Glad to help and thank you for the incredible work on stylelint. It really is a great tool and I cannot believe how underutilized it is.

2024-11-14 00:55 UTC, ybiquitous approved these changes
Thank you, this is now much improved! 👍🏼

2024-11-14 00:55 UTC, merged